### ISSUE TITLE
[Question] Gallery

### ISSUE THREAD

**Issue by GreenLunar** [nestoris/Win98SE#10]
Hello,

I like your work.
How do you generate the `icons.html` gallery files?

Thanks!

**Comment by nestoris** [comment]
Hello!
It's not me -- it's [Grassmunk](https://github.com/grassmunk) -- he generated.

**Comment by nestoris** [comment]
I have an awk script for it... I can publish it soon.

**Comment by nestoris** [comment]
> 

https://github.com/nestoris/Win98SE/tree/main/SE98 -- the two last scripts in `README.md` are for what you ask.

**Comment by GreenLunar** [comment]
On Sun, 27 Nov 2022 06:41:04 -0800
Evgeny Dobromilsky ***@***.***> wrote:

> >
>
> https://github.com/nestoris/Win98SE/tree/main/SE98 -- the two last
> scripts in `README.md` are for what you ask.
>

Thank you, Evgeny (:
